require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  DisplayStyleGuide: true
  Include:
    - '**/*.rb'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'

Layout/LineLength:
  IgnoredPatterns: ['\A\s*#']
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Gemfile'
    - 'config/routes.rb'
    - 'config/environments/**/*'

RSpec/NamedSubject:
  Enabled: false

RSpec/DescribeClass:
   Exclude:
    - 'spec/views/**/*'

Metrics/AbcSize:
   Exclude:
    - 'app/controllers/*'

Metrics/MethodLength:
   Exclude:
    - 'app/controllers/*'

RSpec/ExampleLength:
   Exclude:
    - 'spec/features/*'

RSpec/ImplicitExpect:
  Description: Check that a consistent implicit expectation style is used.
  Enabled: true
  EnforcedStyle: should
  SupportedStyles:
    - is_expected
    - should
  VersionAdded: '1.8'
  StyleGuide: https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitExpect

RSpec/ImplicitSubject:
  Description: Checks for usage of implicit subject (`is_expected` / `should`).
  Enabled: true
  EnforcedStyle: single_line_only
  SupportedStyles:
    - single_line_only
    - single_statement_only
    - disallow
  VersionAdded: '1.29'
  VersionChanged: '1.30'
  StyleGuide: https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ImplicitSubject